### ISSUE TITLE
Add note explanation about user group 'All' in customize_installer section

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-docs#263]
This docs enhancement was born during [this](https://github.com/akeneo/pim-community-dev/issues/4065) discussion. 

According to @nidup group 'All':

> The group "all" never appears in the user management UI, neither in group list, neither in user edit, it's a system group added for any users created in the PIM. cf http://demo.akeneo.com/#url=/user/group

> It's mainly used in Enterprise Edition to grant permissions to any users and appears in "permissions" tabs of "locale", "attribute", "category", etc (in the Enterprise Edition only).

As I think many new comers will have problem during custom installation trying to translate user group 'All' with others groups. And we have to add note about it in the ```customize_installer``` section.

**Comment by nidup** [comment]
Hi @a2xchip
Thank you for raising the issue here!
I do agree, I think that the "customize_installer" section should explain that all data contained in the minimal data fixtures is mandatory (https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/InstallerBundle/Resources/fixtures/minimal).
When a dev created its own configuration, he can copy it and complete it but some values can't be changed, he must keep:
 - "All" user group
 - "other" attribute group
 - have only one mandatory "pim_catalog_identifier" attribute (sku by default)
 - have at least a channel and a category tree

Are you interested to open a Pull Request on 1.5 branch to complete this cookbook?

**Comment by a2xchip** [comment]
@nidup I will very pleased to try it ))

**Comment by a2xchip** [comment]
Should I branch from master or 1.5? @nidup

**Comment by nidup** [comment]
Thank you! 1.5 is better for the doc, don't hesitate if you need any further information :)
