### ISSUE TITLE
Attibute types listing

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-docs#267]
Akeneo PIM has built in attribute data types. But there is no information about it in the docs section. 

We may add built in attributes data types list with explanations how to use them in imports and customized installation. Todays newcomers have to browse source code to find right attribute data types and how to use them. 

Documentation branch 1.2 has such [page](http://docs.akeneo.com/1.2/references/basic/technical_entities.html#attribute) but it disappeared in the future versions.

* pim_catalog_identifier
* pim_catalog_text
* pim_catalog_number
* pim_catalog_boolean
* pim_catalog_price_collection
* etc

Each type in list may be linked to dedicated page with further information (like form types listing in symfony book).

**Comment by nidup** [comment]
Hi @a2xchip !

Yes, we should re-integrate this page in the reference section, maybe starting by a "Product Information" page containing the previous 1.2 content and the list of attribute types. Then we'll be able to add cookbook about customizing these attribute types and how to create a very new attribute type (this cookbook is very expected).

By the way, since we dropped this page, we wrote some user guides that contain complementary functional info https://www.akeneo.com/user-guide/ but these extra doc are not easy to find from the tech doc, we could add a link

Don't hesitate to open the PR, I would be glad to work with you on the first version of this page :)

**Comment by jmleroux** [comment]
What about a command to list all available types in the app ?
It could list event custom attributes.
Just an idea...

**Comment by a2xchip** [comment]
@nidup I tried to find information in user guides (1.4) and couldn't. Is it better to add PR to 1.5 branch too? 
I will think about page/pages structure and content and post it here for discussion with you before creating PR.

@jmleroux I think it will be helpful even for developers that implemented and use many custom types. Is it possible to intersect tickets between doc and project repos?

**Comment by nidup** [comment]
We can add PR on 1.5 for doc, we'll merge to master before the 1.6 release.
Good idea for the cmd which list available attribute type, i would create a dedicated improvement for this, we already talking about something similar, it was more to check that a custom attribute type is properly configured with all tagged services etc

**Comment by a2xchip** [comment]
@nidup Cool!

**Comment by a2xchip** [comment]
Listed ))
