### ISSUE TITLE
Document about akeneo command lines

### ISSUE THREAD

**Issue by ghost** [akeneo/pim-docs#621]
Hello,

I would like to contribute to the documentation with a list of available commands in akeneo with description, arguments and specific options.

Only akeneo, pim and pimee commands are concerned.

Are you interested about it?

Regards,

Benjamin

**Comment by mickaelandrieu** [comment]
Hello @DnD-Tuk,

yes we are and we can help you :)

Let me know if you need help, I'm here for you.

Mickaël

**Comment by fitn** [comment]
Hello @ghost

I close this ticket for the reason that @jmleroux explained in your PR #627 

I agree this documentation should be added here. Anyway, we are not able today to correctly manage our outdated documentation. And this is exactly, the kind of documentation that we will be outdated in few months :/
I apologize because you already take time to create the PR.
