### ISSUE TITLE
In TreeListener.php line 72: Tree object class: Pim\Bundle\CatalogBundle\Entity\Category must have tree metadata at this point 

### ISSUE THREAD

**Issue by kamranmalikawan** [akeneo/pim-docs#801]
Hi All,

I have facing this issue when adding a new field in category using 2.1 version of Akeneo i spent lot of time on that but not able to fix please help on that.

Thanks,

**Comment by tamarasaurus** [comment]
Hi @kamranmalikawan, for bugs with the pim, you can create an issue at https://github.com/akeneo/pim-community-dev/issues instead.

Regards,
Tamara

**Comment by karthik32cse** [comment]
Solution:
-----------
The above issue is occured due to the DependencyInjection. In order to fix this issue follow the below instructions,

Creating an Extension Class:
----------------------------------------
1. It has to live in the DependencyInjection namespace of the bundle;
2. It has to implement the ExtensionInterface, which is usually achieved by extending the Extension class;
3. The name is equal to the bundle name with the Bundle suffix replaced by Extension (e.g. the Extension class of the AcmeBundle would be called AcmeExtension and the one for AcmeCatalogBundle would be called AcmeCatalogExtension).

Code:
-------
**# /src/Acme/Bundle/CatalogBundle/DependencyInjection/AcmeCatalogExtension.php**	
`<?php

namespace Acme\Bundle\CatalogBundle\DependencyInjection;

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader;
use Symfony\Component\HttpKernel\DependencyInjection\Extension;

class AcmeCatalogExtension extends Extension
{
    public function load(array $configs, ContainerBuilder $container)
    {
        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('entities.yml');
    }
}`

_Let me know if you have any questions_ 

Regards,
Karthik Dhakshinamoorthy
